package daio7771.dioriteisntuseless.registry

import daio7771.dioriteisntuseless.Dioriteisntuseless
import net.minecraft.core.Registry
import net.minecraft.core.registries.BuiltInRegistries
import net.minecraft.sounds.SoundEvent

/**
 * The mod's own sounds (assets/dioriteisntuseless/sounds.json). The .ogg files are generated by
 * tools/generate_sounds.py (Morse) and tools/generate_ambience.py (background).
 */
object ModSounds {

    /** Short, soft Morse beep (dot). */
    val MORSE_DOT: SoundEvent = register("morse.dot")

    /** Long, soft Morse beep (dash). */
    val MORSE_DASH: SoundEvent = register("morse.dash")

    /** Unsettling Abuse Mode background, looping: levels 1 to 4 and the ending (index = level - 1). */
    val AMBIENCE: List<SoundEvent> = listOf("level1", "level2", "level3", "level4", "final").map { register("ambience.$it") }

    private fun register(name: String): SoundEvent {
        val id = Dioriteisntuseless.id(name)
        return Registry.register(BuiltInRegistries.SOUND_EVENT, id, SoundEvent.createVariableRangeEvent(id))
    }

    /** Call from onInitialize: accessing the object already registers the sounds. */
    fun init() {}
}
